### PR TITLE
nicer display of an all-forfeits season

### LINKED ISSUE #130: triple-forfeit displays wrong
image

### PR DESCRIPTION
**Pull request by FoxLisk**
fixes #130

### CODE REVIEW

File: src/web/mod.rs [hunk 1]
```diff
@@ -592,13 +592,18 @@ fn get_standings_context(
                         .cloned()
                         .unwrap_or("Unknown".to_string());
 
+                    let avg = if s.avg_time_finished() > 0.0 {
```
Comment (FoxLisk) [inline src/web/mod.rs:595]: this isnt the most elegant solution but it's fine

**Comment by FoxLisk** [comment]
image

**Review by RequiemOfSpirit — APPROVED** [review]
